### ISSUE TITLE
Is this project still active - will we get regular updates again for rooted devices?

### ISSUE THREAD

**Issue by joeyoropesa-dev** [vendetta-mod/VendettaXposed#13]
The question written above as an title 👍

**Comment by wingio** [comment]
The module is still being updated, theres just nothing new needed atm

**Comment by joeyoropesa-dev** [comment]
> The module is still being updated, theres just nothing new needed atm

Well in that case bugs like emote reaction bug (spams when I try ti react on an message) is a part of the Alpha/Beta build that needs to be fixed by Discord - the mod didn't make it buggy, but the whole client itself is buggy like that 😅😅
