### ISSUE TITLE
Module not usable on cloned instances of Discord app

### ISSUE THREAD

**Issue by MeguminSama** [vendetta-mod/VendettaXposed#3]
Consider removing this line https://github.com/vendetta-mod/VendettaXposed/blob/9e42c323b3169b452713e6e1bb12074ef46716b3/app/src/main/java/com/vendetta/xposed/Main.kt#L37

LSPosed has a "recommended" label and highlights the discord app anyways, so this feels redundant, and removing it will allow people to have a vanilla and modded instance separately.

**Comment by maisymoe** [comment]
This is a problem I have encountered personally, and I forgot this line was even in the codebase. Will remove when I get the chance :)
